# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build termuxcn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build termuxcn
      run: ./gradlew assembleDebug
    - name: Store generated universal APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-arm64-v8a
        path: |
          ./app/build/outputs/apk/debug/termux-app-arm64-v8a-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
    - name: Store generated armeabi-v7a APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-armeabi-v7a
        path: |
          ./app/build/outputs/apk/debug/termux-app-armeabi-v7a-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json

    - name: Store generated arm64-v8a APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-arm64-v8a
        path: |
          ./app/build/outputs/apk/debug/termux-app-arm64-v8a-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
     - name: Store generated armeabi-v7a APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app-armeabi-v7a
        path: |
          ./app/build/outputs/apk/debug/termux-app-armeabi-v7a-debug.apk
          ./app/build/outputs/apk/debug/output-metadata.json
